language: node_js
node_js:
- 8.9.0
cache:
  directories:
  - node_modules
before_install:
- npm install hexo-cli -g
install:
- npm install
script:
- hexo clean
- hexo generate
after_script:
  - cd ./public
  - git init
  - git config user.name "weipengjun"
  - git config user.email "835500598@qq.com"
  - git add .
  - git commit -m "updete blog"
  # Github Pages
  - git push --force --quiet "https://${CL_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  # - git push --force --quiet "https://coding用户名:${CO_TOKEN}@${CO_REF}" master:master

branches:
  only:
  - next
env:
 global:
   # Github Pages
   - GH_REF: github.com/weipengjun/weipengjun.github.io
   # Coding Pages
  #  - CO_REF: git.coding.net/weipengjun/weipengjun.coding.me.git
